version: "3.9"

services:
  app:
    image: registry.example.com/sales-assistant:latest
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      ENVIRONMENT: production
      LOG_LEVEL: INFO
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    networks:
      - backend

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assistant
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - backend

  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
